spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}